### ISSUE TITLE
Rails Journey Tracker

### ISSUE THREAD

**Issue by Justicea83** [Justicea83/rails-journey#1]
- [ ] Introduction and setup.
- [ ] The ruby programming language.
- [ ] Introduction to ruby on rails.
- [ ] Crud operations in Ruby.
- [ ] Styling of your rails application
- [ ] Associations and Authentication Systems
